### ISSUE TITLE
Erro Install

### ISSUE THREAD

**Issue by rodrigophpweb** [MaxKellermann/svg2pes#5]
Hello, I am with erro in Installation:

make[1]: Entering directory '/home/rodrigo/svg2pes'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c svg2pes '/usr/local/bin'
/usr/bin/install: não foi possível criar arquivo comum '/usr/local/bin/svg2pes': Permissão negada
Makefile:359: recipe for target 'install-binPROGRAMS' failed
make[1]: *** [install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home/rodrigo/svg2pes'
Makefile:737: recipe for target 'install-am' failed
make: *** [install-am] Error 2

**Comment by MaxKellermann** [comment]
You specified a prefix (`/usr/local`, the default) where your current user has no write permissions. This is a generic problem not specific to svg2pes. Try `./configure --prefix=$HOME/opt/svg2pes` or so.
